name: ORT Scan Tiny Express (MIT)

on:
  workflow_dispatch:

jobs:
  ort-analysis-and-scan:
    runs-on: ubuntu-latest
    timeout-minutes: 15  # Much shorter timeout since project is tiny

    steps:
      - name: Create tiny-express project
        run: |
          mkdir -p tiny-express
          cd tiny-express
          echo '{
            "name": "tiny-express-mit",
            "version": "1.0.0",
            "license": "MIT",
            "dependencies": {
              "express": "4.18.2",
              "morgan": "1.10.0"
            }
          }' > package.json
          npm install --silent

      - name: Add MIT license file
        run: |
          cat <<EOF > tiny-express/LICENSE
          MIT License

          Copyright (c) $(date +%Y) Test User

          Permission is hereby granted...
          EOF

      - name: Create ORT directories
        run: |
          mkdir -p ort-output ort-config
          sudo chmod -R 777 ort-output

      - name: Configure ORT
        run: |
          cat <<EOF > ort-config/config.yml
          ort:
            analyzer:
              allowDynamicVersions: true
            scanner:
              ignorePatterns:
                - "**/node_modules/**"
          EOF

      - name: Run ORT analyze
        run: |
          echo "Starting analysis at $(date)"
          docker run --rm \
            -v ${{ github.workspace }}/tiny-express:/project \
            -v ${{ github.workspace }}/ort-output:/out \
            -v ${{ github.workspace }}/ort-config:/ort/config \
            ghcr.io/oss-review-toolkit/ort:latest \
            analyze -i /project -o /out
          echo "Analysis finished at $(date)"

      - name: Run ORT scan
        run: |
          echo "Starting scan at $(date)"
          docker run --rm \
            -v ${{ github.workspace }}/tiny-express:/project \
            -v ${{ github.workspace }}/ort-output:/out \
            -v ${{ github.workspace }}/ort-config:/ort/config \
            ghcr.io/oss-review-toolkit/ort:latest \
            scan -i /out/analyzer-result.yml -o /out
          echo "Scan finished at $(date)"

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: ort-tiny-express-results
          path: ort-output/
