name: ORT Scan for tiny-express

on:
  workflow_dispatch:

jobs:
  ort-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # Required for cloning

    steps:
      # 1. CLONE WITH PROPER AUTHENTICATION
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          # If repository is in same org, you can omit the full path
          repository: OSS-PRO/source_projects  # Double-check this name
          path: source_projects
          token: ${{ secrets.PAT_TOKEN || secrets.GITHUB_TOKEN }}  # Use PAT for private repos
          fetch-depth: 0

      # 2. DEBUG: Verify repository contents
      - name: List repository contents
        run: |
          ls -la source_projects/
          if [ -d "source_projects/tiny-express" ]; then
            ls -la source_projects/tiny-express/
          else
            echo "::error::tiny-express directory not found!"
            exit 1
          fi

      # ... rest of your ORT scanning steps ...
