name: ORT Scan Tiny Express Project

on:
  workflow_dispatch:

jobs:
  ort-scan:
    runs-on: ubuntu-latest
    timeout-minutes: 5  # Very short timeout for quick testing

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up tiny-express project
        run: |
          mkdir -p tiny-express
          cd tiny-express
          
          cat <<EOF > package.json
          {
            "name": "tiny-express-mit",
            "version": "1.0.0",
            "license": "MIT",
            "dependencies": {
              "express": "4.18.2",
              "morgan": "1.10.0"
            }
          }
          EOF
          
          npm install --silent
          
          # Set full permissions for ORT
          chmod -R 777 .

      - name: Set up ORT environment
        run: |
          mkdir -p ort-config ort-output
          chmod -R 777 ort-output
          
          cat <<EOF > ort-config/config.yml
          ort:
            analyzer:
              allowDynamicVersions: true
              temp_dir: /tmp/ort
              enabled_package_managers: ["NPM"]  # Only enable NPM
            scanner:
              ignorePatterns:
                - "**/node_modules/**"
          EOF

      - name: Run ORT analyze (with fixed permissions)
        run: |
          echo "Starting ORT analysis at $(date)"
          docker run --rm \
            -v ${{ github.workspace }}/tiny-express:/project \
            -v ${{ github.workspace }}/ort-output:/ort/output \
            -v ${{ github.workspace }}/ort-config:/ort/config \
            -e ORT_CONFIG_DIR=/ort/config \
            -e ORT_DATA_DIR=/tmp/ort-data \
            -w /project \
            ghcr.io/oss-review-toolkit/ort:latest \
            analyze -i /project -o /ort/output \
            --package-curations-file /ort/config/curations.yml
          echo "Finished ORT analysis at $(date)"

      - name: Run ORT scan
        run: |
          echo "Starting ORT scan at $(date)"
          docker run --rm \
            -v ${{ github.workspace }}/tiny-express:/project \
            -v ${{ github.workspace }}/ort-output:/ort/output \
            -v ${{ github.workspace }}/ort-config:/ort/config \
            ghcr.io/oss-review-toolkit/ort:latest \
            scan -i /ort/output/analyzer-result.yml -o /ort/output
          echo "Finished ORT scan at $(date)"

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: ort-tiny-express-results
          path: ort-output/
