name: ORT Scan for tiny-express

on:
  workflow_dispatch:

jobs:
  ort-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # Required for cloning

    steps:
      # 1. PROPERLY CLONE THE REPOSITORY
      - name: Clone source_projects
        uses: actions/checkout@v4
        with:
          repository: OSS-PRO/source_projects
          path: source_projects
          token: ${{ secrets.GITHUB_TOKEN }}

      # 2. VERIFY THE REPO STRUCTURE
      - name: Check tiny-express exists
        run: |
          if [ ! -d "source_projects/tiny-express" ]; then
            echo "::error::tiny-express directory not found!"
            ls -R source_projects  # Debug listing
            exit 1
          fi

      # 3. SETUP ORT ENVIRONMENT
      - name: Prepare ORT
        run: |
          mkdir -p ort-{output,config}
          echo "ORT directories created:"
          ls -l ort-*

      # 4. ORT CONFIGURATION
      - name: Configure ORT
        run: |
          cat <<EOF > ort-config/config.yml
          ort:
            analyzer:
              allowDynamicVersions: true
            scanner:
              ignorePatterns:
                - "**/node_modules/**"
                - "**/test/**"
                - "**/.git/**"
          EOF

      # 5. RUN ANALYSIS
      - name: ORT Analyze
        run: |
          docker run --rm \
            -v "$PWD/source_projects/tiny-express:/project" \
            -v "$PWD/ort-output:/ort/output" \
            -v "$PWD/ort-config:/ort/config" \
            ghcr.io/oss-review-toolkit/ort:latest \
            analyze -i /project -o /ort/output

      # 6. RUN SCAN
      - name: ORT Scan
        run: |
          docker run --rm \
            -v "$PWD/ort-output:/ort/output" \
            -v "$PWD/ort-config:/ort/config" \
            ghcr.io/oss-review-toolkit/ort:latest \
            scan -i /ort/output/analyzer-result.yml -o /ort/output

      # 7. UPLOAD RESULTS
      - name: Upload ORT Report
        uses: actions/upload-artifact@v4
        with:
          name: ort-scan-results
          path: |
            ort-output/analyzer-result.yml
            ort-output/scan-result.yml
