name: ORT scan for tiny-express

on:
  workflow_dispatch:

jobs:
  ort-analysis-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        run: |
          git clone https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/OSS-PRO/source_projects.git
          ls source_projects  # Verify contents

      - name: Verify tiny-express exists
        run: |
          [ -d "source_projects/tiny-express" ] || { echo "tiny-express directory not found"; exit 1; }

      - name: Setup ORT environment
        run: |
          mkdir -p ort-{output,config}
          sudo chmod -R 777 ort-output

      - name: Configure ORT
        run: |
          cat <<EOF > ort-config/config.yml
          ort:
            analyzer:
              allowDynamicVersions: true
            scanner:
              ignorePatterns:
                - "**/node_modules/**"
          EOF

      - name: Run ORT analysis
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/source_projects/tiny-express:/project \
            -v ${{ github.workspace }}/ort-output:/ort/output \
            -v ${{ github.workspace }}/ort-config:/ort/config \
            ghcr.io/oss-review-toolkit/ort:latest \
            analyze -i /project -o /ort/output

      - name: Run ORT scan
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/ort-output:/ort/output \
            -v ${{ github.workspace }}/ort-config:/ort/config \
            ghcr.io/oss-review-toolkit/ort:latest \
            scan -i /ort/output/analyzer-result.yml -o /ort/output

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: ort-results
          path: ort-output
