name: ORT Scan Workflow

on: [workflow_dispatch]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository with authentication
        run: |
          # Clone using GitHub Actions' built-in token
          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/OSS-PRO/source_projects.git
          
          # Verify the repository was cloned
          ls -la source_projects
          
          # Verify tiny-express exists
          [ -d "source_projects/tiny-express" ] || { echo "Error: tiny-express directory not found"; exit 1; }

      - name: Setup ORT environment
        run: |
          mkdir -p ort-{output,config}
          sudo chmod -R 777 ort-output

      - name: Configure ORT
        run: |
          cat <<EOF > ort-config/config.yml
          ort:
            analyzer:
              allowDynamicVersions: true
            scanner:
              ignorePatterns:
                - "**/node_modules/**"
          EOF

      - name: Run ORT analysis
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/source_projects/tiny-express:/project \
            -v ${{ github.workspace }}/ort-output:/ort/output \
            -v ${{ github.workspace }}/ort-config:/ort/config \
            ghcr.io/oss-review-toolkit/ort:latest \
            analyze -i /project -o /ort/output

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: ort-results
          path: ort-output
