name: ORT scan for tiny-express

on:
  workflow_dispatch:

jobs:
  ort-analysis-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Clone full source_projects repository
        run: |
          mkdir -p source_projects
          git clone https://github.com/OSS-PRO/source_projects.git source_projects/source_projects

      - name: Create ORT config and output directories
        run: |
          mkdir -p ort-output ort-config
          sudo chmod -R 777 ort-output

      - name: Write ORT config
        run: |
          cat <<EOF > ort-config/config.yml
          ort:
            analyzer:
              allowDynamicVersions: true
            scanner:
              ignorePatterns:
                - "**/node_modules/**"
          EOF

      - name: Run ORT analyze on tiny-express
        run: |
          docker run --rm \
            -u root \
            -e ORT_CONFIG_DIR=/ort/config \
            -v ${{ github.workspace }}/source_projects/source_projects/tiny-express:/project \
            -v ${{ github.workspace }}/ort-output:/ort/output \
            -v ${{ github.workspace }}/ort-config:/ort/config \
            ghcr.io/oss-review-toolkit/ort:latest \
            analyze -i /project -o /ort/output

      - name: Run ORT scan
        run: |
          docker run --rm \
            -u root \
            -e ORT_CONFIG_DIR=/ort/config \
            -v ${{ github.workspace }}/source_projects/source_projects/tiny-express:/project \
            -v ${{ github.workspace }}/ort-output:/ort/output \
            -v ${{ github.workspace }}/ort-config:/ort/config \
            ghcr.io/oss-review-toolkit/ort:latest \
            scan -i /ort/output/analyzer-result.yml -o /ort/output

      - name: Upload ORT output
        uses: actions/upload-artifact@v4
        with:
          name: ort-results
          path: ort-output/
