name: ORT scan express subproject

on:
  workflow_dispatch:

jobs:
  ort-analysis-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout express repo with full Git history
        run: |
          mkdir -p source_projects
          git clone https://github.com/expressjs/express.git source_projects/express

      - name: Create ORT config and output directories
        run: |
          mkdir -p ort-output ort-config
          sudo chmod -R 777 ort-output

      - name: Write ORT config with scanner ignorePatterns
        run: |
          cat <<EOF > ort-config/config.yml
          ort:
            analyzer:
              allowDynamicVersions: true
            scanner:
              ignorePatterns:
                - "**/node_modules/**"
          EOF

      - name: Debug ORT config
        run: cat ort-config/config.yml

      - name: Run ORT analyze
        run: |
          echo "Starting ORT analysis at $(date)"
          docker run --rm \
            -u root \
            -e ORT_CONFIG_DIR=/ort/config \
            -v ${{ github.workspace }}/source_projects/express:/project \
            -v ${{ github.workspace }}/ort-output:/ort/output \
            -v ${{ github.workspace }}/ort-config:/ort/config \
            ghcr.io/oss-review-toolkit/ort:latest \
            analyze -i /project -o /ort/output
          echo "Finished ORT analysis at $(date)"

      - name: Remove node_modules before scan (optional but safe)
        run: |
          echo "Removing node_modules to speed up scan..."
          find source_projects/express -type d -name "node_modules" -prune -exec rm -rf '{}' +
          echo "Cleanup complete."

      - name: Run ORT scan
        run: |
          echo "Starting ORT scan at $(date)"
          docker run --rm \
            -u root \
            -e ORT_CONFIG_DIR=/ort/config \
            -v ${{ github.workspace }}/source_projects/express:/project \
            -v ${{ github.workspace }}/ort-output:/ort/output \
            -v ${{ github.workspace }}/ort-config:/ort/config \
            ghcr.io/oss-review-toolkit/ort:latest \
            scan -i /ort/output/analyzer-result.yml -o /ort/output
          echo "Finished ORT scan at $(date)"

      - name: Upload ORT output as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ort-results
          path: ort-output/
